AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

